version: "2"

services:
    server:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./src/main:/src/main
        environment:
            - FLASK_APP=/src/main/app.py
        command: flask run --host 0.0.0.0 --port 5000