version: 2.1

jobs:
    run_tests:
        docker:
            - image: circleci/python:stretch
        steps:
            - checkout
            - run:
                name: Install Flask Dependencies
                command: |
                    echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
                    pip3 install --user -r requirements.txt
            - run:
                name: Run Unit Tests
                command: |
                    pytest --html=test-reports/pytest_report.html --self-contained-html /src/test/server_test.py
            - store_test_results:
                path: test-reports
            - store_artifacts:
                path: test-reports

workflows:
    build_test:
        jobs:
            - run_tests